;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Character.State.Parrying",NewTagName="Character.State.ParryWindow")
+GameplayTagList=(Tag="Character.Action.Fixed.Dodge",DevComment="이동이 제한되는 액션")
+GameplayTagList=(Tag="Character.Action.Fixed.Parry",DevComment="이동이 제한되는 액션")
+GameplayTagList=(Tag="Character.Action.Movable.Aiming",DevComment="이동하며 가능한 액션")
+GameplayTagList=(Tag="Character.Action.Movable.Attack",DevComment="이동이 가능한 액션")
+GameplayTagList=(Tag="Character.Action.Movable.Sprint",DevComment="이동하며 가능한 액션")
+GameplayTagList=(Tag="Character.State.IFrame",DevComment="")
+GameplayTagList=(Tag="Character.State.ParryWindow",DevComment="")
+GameplayTagList=(Tag="Character.State.Weapon.Bow",DevComment="")
+GameplayTagList=(Tag="Character.State.Weapon.Gun",DevComment="")
+GameplayTagList=(Tag="Character.Status.Exhausted",DevComment="")
+GameplayTagList=(Tag="Game.State.GameOver",DevComment="")
+GameplayTagList=(Tag="Game.State.MainMenu",DevComment="")
+GameplayTagList=(Tag="Game.State.Paused",DevComment="")
+GameplayTagList=(Tag="Game.State.Playing",DevComment="")
+GameplayTagList=(Tag="Game.State.Quit",DevComment="")
+GameplayTagList=(Tag="Game.State.UpgradeSelecting",DevComment="")
+GameplayTagList=(Tag="Room.State.Actived",DevComment="")
+GameplayTagList=(Tag="Room.State.Cleared",DevComment="")
+GameplayTagList=(Tag="Room.State.Idle",DevComment="")
+GameplayTagList=(Tag="Room.State.MoveNext",DevComment="")

