;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Character.Action.Aiming",DevComment="")
+GameplayTagList=(Tag="Character.Action.Attack",DevComment="")
+GameplayTagList=(Tag="Character.Action.Dodge",DevComment="")
+GameplayTagList=(Tag="Character.Action.Parry",DevComment="")
+GameplayTagList=(Tag="Character.Action.Sprint",DevComment="")
+GameplayTagList=(Tag="Character.State.Weapon.Bow",DevComment="")
+GameplayTagList=(Tag="Character.State.Weapon.Gun",DevComment="")
+GameplayTagList=(Tag="Character.Status.Exhausted",DevComment="")
+GameplayTagList=(Tag="Game.State.GameOver",DevComment="")
+GameplayTagList=(Tag="Game.State.MainMenu",DevComment="")
+GameplayTagList=(Tag="Game.State.Paused",DevComment="")
+GameplayTagList=(Tag="Game.State.Playing",DevComment="")
+GameplayTagList=(Tag="Game.State.Quit",DevComment="")
+GameplayTagList=(Tag="Game.State.UpgradeSelecting",DevComment="")
+GameplayTagList=(Tag="Room.State.Actived",DevComment="")
+GameplayTagList=(Tag="Room.State.Cleared",DevComment="")
+GameplayTagList=(Tag="Room.State.Idle",DevComment="")
+GameplayTagList=(Tag="Room.State.MoveNext",DevComment="")

